### ISSUE TITLE
Make a warning about coinjoin.io in README.md

### ISSUE THREAD

**Issue by balodja** [apoelstra/coinjoin#5]
Please, inform the people that those scam services are not related to you in any ways.

**Comment by apoelstra** [comment]
Good idea. Done.

**Comment by b3pio** [comment]
Might want to add both https://coinjoin.cash/ and https://www.unlockingblockchainafrica.io/ aswell. They seem to be copies of the coinjoin.io scam site and aswell the Github menu link on both of these websites link back to your Github.

**Comment by apoelstra** [comment]
Ugh. Sure, done. Thanks for the heads up!

**Comment by Coinbug** [comment]
I might suggest you moving your coinjoin content to a different page and putting up top of the page that's linked to CoinJoin.io that "COINJOIN.IO WEBSITE IS A SCAM!!!". Otherwise, unless someone is half as smart as you, they'll just take a quick look, and suppose it's legit. You would be doing a kindness to coinless people. But I understand it would be annoying to move your material.
This is what I saw: My attention went to right side of the page, I never scrolled down.
![image](https://user-images.githubusercontent.com/102889731/161802876-7e7028f7-e1ee-4acc-98df-6268e50bf4c6.png)

**Comment by apoelstra** [comment]
For sure, I'll edit the `About` section. But I definitely won't link to coinjoin.io on any page(s) that I control.

**Comment by Coinbug** [comment]
Thank you!
