### ISSUE TITLE
coinjoin.io is down

### ISSUE THREAD

**Issue by iraykhel** [apoelstra/coinjoin#8]
I got the assholes taken down after getting scammed by them. Took a few threats of class action suit against their domain registrar namecheap.com. Wanted to let you know.

**Comment by apoelstra** [comment]
Thanks!!

**Comment by b3pio** [comment]
@iraykhel Sorry to hear about your loss, but this scam site (coinjoin.io & its duplicate: coinjoin.cash) seem to be still/back online to me. Only duplicate site which looks to be currently down is unlockingblockchainafrica.io

**Comment by iraykhel** [comment]
Goddammit, they were down for a day and I thought they were done for

**Comment by iraykhel** [comment]
They switched the registrar to tucows. Will see about contacting tucows. For now, google no longer returns coinjoin.io when looking for "bitcoin mixer". Of course, the rest of the results are also probably scams.

**Comment by b3pio** [comment]
I've been tracking numerous of them (contemplating making a repo just to list them all and hopefully get it to rank high in search engine results to prevent people being scammed in the future), because sadly the web is rife with scam 'coin mixers' and like you've experienced they just pop up again a day later with another domain/host provider. Just have to be persistant with takedowns.. And once the search engine bot crawls the new site they will be back in the results again too unfortunately. TRUST NO WEBSITE to 'mix' your coins. Samourai and Wasabi wallets are probably the only 2 I personally would trust.

**Comment by Coinbug** [comment]
Thank you iraykhel and b3pio for your work at getting Coinjoin taken down! and to apoelstra for hosting these conversations! I left a voice message with the FBI about Coinjoin.io, not sure if I mentioned Coinjoin.cash of the unlockingblockchainafrica.io.
